import type { Category, FoodItem, NutritionalFacts } from '../types';
import type { WeekdayKey } from './dates';

function nf(partial: Partial<NutritionalFacts> & Pick<NutritionalFacts, 'calories' | 'proteinG'>): NutritionalFacts {
  return {
    servingSize: partial.servingSize ?? '1 portion (estimated)',
    calories: partial.calories,
    totalFatG: partial.totalFatG ?? 12,
    saturatedFatG: partial.saturatedFatG ?? 4,
    cholesterolMg: partial.cholesterolMg ?? 45,
    sodiumMg: partial.sodiumMg ?? 420,
    totalCarbG: partial.totalCarbG ?? 28,
    dietaryFiberG: partial.dietaryFiberG ?? 3,
    totalSugarsG: partial.totalSugarsG ?? 4,
    proteinG: partial.proteinG,
  };
}

function img(seed: string): string {
  const q = encodeURIComponent(seed);
  return `https://picsum.photos/seed/${q}/800/600`;
}

interface Seed {
  name: string;
  price: number;
  unitLabel: string;
  qty: number;
  description: string;
  ingredients: string[];
  nutrition: NutritionalFacts;
}

function item(
  weekday: WeekdayKey,
  category: Category,
  index: number,
  seed: Seed,
): FoodItem {
  const id = `${weekday}-${category}-${index}`;
  return {
    id,
    category,
    name: seed.name,
    price: seed.price,
    unitLabel: seed.unitLabel,
    quantityAvailable: seed.qty,
    imageUrl: img(id),
    description: seed.description,
    ingredients: seed.ingredients,
    nutrition: seed.nutrition,
  };
}

/** Five protein names per weekday (rotating copy). */
const PROTEIN_ROTATIONS: Record<WeekdayKey, Seed[]> = {
  monday: [
    {
      name: 'Smoked paprika chicken thighs',
      price: 48,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 12,
      description: 'Bone-in thighs finished with lemon, garlic, and a light paprika rub. Juicy and picnic-friendly.',
      ingredients: ['Chicken thighs', 'Smoked paprika', 'Lemon', 'Garlic', 'Olive oil', 'Kosher salt', 'Black pepper'],
      nutrition: nf({ calories: 320, proteinG: 28, totalFatG: 18, sodiumMg: 520 }),
    },
    {
      name: 'Herb-crusted salmon',
      price: 62,
      unitLabel: 'Half-tray (serves ~6)',
      qty: 8,
      description: 'Atlantic salmon with dill, parsley, and a mustard glaze. Baked until just flaky.',
      ingredients: ['Salmon', 'Dijon mustard', 'Dill', 'Parsley', 'Lemon zest', 'Olive oil'],
      nutrition: nf({ calories: 290, proteinG: 26, totalFatG: 16, cholesterolMg: 65 }),
    },
    {
      name: 'Slow-cooked beef barbacoa',
      price: 56,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 10,
      description: 'Chuck roast braised with chipotle, cumin, and onion until shreddable. Mild heat.',
      ingredients: ['Beef chuck', 'Chipotle in adobo', 'Cumin', 'Onion', 'Garlic', 'Bay leaf', 'Apple cider vinegar'],
      nutrition: nf({ calories: 340, proteinG: 30, totalFatG: 18, sodiumMg: 580 }),
    },
    {
      name: 'Garlic-lime pork tenderloin',
      price: 52,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 9,
      description: 'Roasted medallions with a bright cilantro-lime finish. Sliced for easy serving.',
      ingredients: ['Pork tenderloin', 'Lime', 'Cilantro', 'Garlic', 'Olive oil', 'Honey', 'Cumin'],
      nutrition: nf({ calories: 260, proteinG: 32, totalFatG: 9 }),
    },
    {
      name: 'Turkey meatballs in tomato basil',
      price: 44,
      unitLabel: 'Half-tray (~24 meatballs)',
      qty: 14,
      description: 'Lean turkey meatballs simmered in a simple tomato-basil sauce.',
      ingredients: ['Ground turkey', 'Tomato', 'Basil', 'Onion', 'Garlic', 'Oregano', 'Breadcrumbs', 'Egg'],
      nutrition: nf({ calories: 240, proteinG: 22, totalFatG: 10, sodiumMg: 480 }),
    },
  ],
  tuesday: [
    {
      name: 'Lemon-rosemary rotisserie chicken',
      price: 46,
      unitLabel: 'Whole bird (serves ~6)',
      qty: 10,
      description: 'Whole chicken rubbed with rosemary and roasted until golden. Carving instructions included.',
      ingredients: ['Chicken', 'Rosemary', 'Lemon', 'Garlic', 'Butter', 'Kosher salt', 'Black pepper'],
      nutrition: nf({ calories: 310, proteinG: 34, totalFatG: 14, cholesterolMg: 110 }),
    },
    {
      name: 'Miso-ginger glazed cod',
      price: 64,
      unitLabel: 'Half-tray (serves ~6)',
      qty: 7,
      description: 'Mild white fish with a sweet-savory miso glaze and scallions.',
      ingredients: ['Cod', 'White miso', 'Ginger', 'Soy sauce', 'Mirin', 'Scallions', 'Sesame oil'],
      nutrition: nf({ calories: 250, proteinG: 27, totalFatG: 9, sodiumMg: 640 }),
    },
    {
      name: 'Carne asada strips',
      price: 58,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 11,
      description: 'Grilled skirt steak with citrus marinade, sliced thin for tacos or bowls.',
      ingredients: ['Skirt steak', 'Orange juice', 'Lime', 'Garlic', 'Cumin', 'Oregano', 'Jalapeño'],
      nutrition: nf({ calories: 330, proteinG: 31, totalFatG: 17 }),
    },
    {
      name: 'Harissa honey chicken drumsticks',
      price: 42,
      unitLabel: 'Tray (~18 pieces)',
      qty: 13,
      description: 'Sticky, lightly spicy drumsticks with sesame seeds and parsley.',
      ingredients: ['Chicken drumsticks', 'Harissa', 'Honey', 'Garlic', 'Paprika', 'Parsley', 'Sesame seeds'],
      nutrition: nf({ calories: 300, proteinG: 24, totalFatG: 15, sodiumMg: 500 }),
    },
    {
      name: 'Red wine braised short ribs',
      price: 68,
      unitLabel: 'Half-tray (serves ~6)',
      qty: 6,
      description: 'Fork-tender ribs in a rich pan sauce with mirepoix and thyme.',
      ingredients: ['Beef short ribs', 'Red wine', 'Carrot', 'Celery', 'Onion', 'Thyme', 'Tomato paste', 'Beef stock'],
      nutrition: nf({ calories: 420, proteinG: 28, totalFatG: 26, sodiumMg: 600 }),
    },
  ],
  wednesday: [
    {
      name: 'Peri-peri quarter chickens',
      price: 50,
      unitLabel: 'Half-tray (2 quarters, serves ~4)',
      qty: 12,
      description: 'Spicy-sweet peri-peri marinade with charred lemon halves.',
      ingredients: ['Chicken', 'Peri-peri sauce', 'Smoked paprika', 'Lemon', 'Garlic', 'Brown sugar'],
      nutrition: nf({ calories: 340, proteinG: 30, totalFatG: 18, sodiumMg: 560 }),
    },
    {
      name: 'Coconut curry shrimp',
      price: 60,
      unitLabel: 'Half-tray (serves ~6)',
      qty: 8,
      description: 'Shrimp in a mild coconut milk curry with bell peppers and basil.',
      ingredients: ['Shrimp', 'Coconut milk', 'Red curry paste', 'Bell pepper', 'Basil', 'Fish sauce', 'Lime'],
      nutrition: nf({ calories: 280, proteinG: 24, totalFatG: 14, cholesterolMg: 180, sodiumMg: 620 }),
    },
    {
      name: 'Maple-mustard pork shoulder',
      price: 54,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 9,
      description: 'Pulled shoulder with a glossy maple-mustard glaze. Comfort-food crowd pleaser.',
      ingredients: ['Pork shoulder', 'Maple syrup', 'Dijon mustard', 'Apple cider vinegar', 'Garlic', 'Onion powder'],
      nutrition: nf({ calories: 360, proteinG: 28, totalFatG: 20 }),
    },
    {
      name: 'Za’atar yogurt chicken skewers',
      price: 46,
      unitLabel: 'Tray (~16 skewers)',
      qty: 14,
      description: 'Boneless breast cubes marinated in yogurt and za’atar, grilled.',
      ingredients: ['Chicken breast', 'Greek yogurt', 'Za’atar', 'Lemon', 'Garlic', 'Olive oil'],
      nutrition: nf({ calories: 230, proteinG: 29, totalFatG: 8, sodiumMg: 440 }),
    },
    {
      name: 'Beef kofta with tahini',
      price: 52,
      unitLabel: 'Half-tray (~20 pieces)',
      qty: 10,
      description: 'Spiced beef kofta drizzled with lemon-tahini sauce and parsley.',
      ingredients: ['Ground beef', 'Onion', 'Parsley', 'Cumin', 'Coriander', 'Tahini', 'Lemon', 'Paprika'],
      nutrition: nf({ calories: 310, proteinG: 26, totalFatG: 18, sodiumMg: 520 }),
    },
  ],
  thursday: [
    {
      name: 'Everything bagel crusted salmon',
      price: 66,
      unitLabel: 'Half-tray (serves ~6)',
      qty: 7,
      description: 'Crispy topped salmon with capers and a cool cucumber yogurt on the side.',
      ingredients: ['Salmon', 'Everything seasoning', 'Capers', 'Cucumber', 'Greek yogurt', 'Dill'],
      nutrition: nf({ calories: 300, proteinG: 27, totalFatG: 17, cholesterolMg: 70 }),
    },
    {
      name: 'Spatchcock BBQ chicken',
      price: 48,
      unitLabel: 'Whole spatchcock (serves ~6)',
      qty: 11,
      description: 'Evenly roasted with a tangy tomato-molasses BBQ glaze.',
      ingredients: ['Chicken', 'Tomato', 'Molasses', 'Smoked paprika', 'Garlic powder', 'Apple cider vinegar'],
      nutrition: nf({ calories: 320, proteinG: 33, totalFatG: 14, sodiumMg: 540 }),
    },
    {
      name: 'Beef kebab platter',
      price: 58,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 10,
      description: 'Sirloin chunks with peppers and onions, lightly charred.',
      ingredients: ['Sirloin', 'Bell pepper', 'Red onion', 'Olive oil', 'Oregano', 'Garlic', 'Smoked paprika'],
      nutrition: nf({ calories: 310, proteinG: 30, totalFatG: 15 }),
    },
    {
      name: 'Crispy chili-lime tofu bites (add-on protein)',
      price: 38,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 15,
      description: 'Extra-firm tofu with cornstarch crisp and chili-lime salt — listed under rotation as requested.',
      ingredients: ['Extra-firm tofu', 'Cornstarch', 'Chili powder', 'Lime zest', 'Garlic', 'Scallions'],
      nutrition: nf({ calories: 190, proteinG: 14, totalFatG: 10, sodiumMg: 380 }),
    },
    {
      name: 'Heritage pork chops with apple',
      price: 56,
      unitLabel: 'Half-tray (6 chops)',
      qty: 8,
      description: 'Pan-seared chops with sautéed apples and thyme.',
      ingredients: ['Pork chops', 'Apple', 'Thyme', 'Butter', 'Shallot', 'Chicken stock', 'Dijon'],
      nutrition: nf({ calories: 350, proteinG: 30, totalFatG: 19, cholesterolMg: 95 }),
    },
  ],
  friday: [
    {
      name: 'Weekend garlic butter lobster rolls (chicken swap)',
      price: 44,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 12,
      description: 'Friday special: garlic butter chicken salad style rolls — hearty and picnic-ready.',
      ingredients: ['Chicken breast', 'Celery', 'Mayonnaise', 'Garlic butter', 'Chives', 'Lemon', 'Split-top buns'],
      nutrition: nf({ calories: 360, proteinG: 24, totalFatG: 18, cholesterolMg: 75 }),
    },
    {
      name: 'Chimichurri flank steak',
      price: 62,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 9,
      description: 'Sliced flank with bright chimichurri and pickled onions.',
      ingredients: ['Flank steak', 'Parsley', 'Oregano', 'Garlic', 'Red wine vinegar', 'Olive oil', 'Red onion'],
      nutrition: nf({ calories: 330, proteinG: 32, totalFatG: 16 }),
    },
    {
      name: 'Tandoori-spiced drumettes',
      price: 40,
      unitLabel: 'Tray (~24 pieces)',
      qty: 14,
      description: 'Yogurt-marinated wings with warm spice and char.',
      ingredients: ['Chicken wings', 'Greek yogurt', 'Garam masala', 'Kashmiri chili', 'Ginger', 'Garlic', 'Lime'],
      nutrition: nf({ calories: 290, proteinG: 23, totalFatG: 16, sodiumMg: 510 }),
    },
    {
      name: 'Seared scallops with brown butter',
      price: 72,
      unitLabel: 'Half-tray (serves ~5)',
      qty: 5,
      description: 'Treat-yourself Friday: scallops with caper brown butter.',
      ingredients: ['Scallops', 'Butter', 'Capers', 'Lemon', 'Parsley', 'Garlic'],
      nutrition: nf({ calories: 260, proteinG: 22, totalFatG: 15, cholesterolMg: 55, sodiumMg: 480 }),
    },
    {
      name: 'Smoky BBQ pulled pork',
      price: 50,
      unitLabel: 'Half-tray (serves ~10)',
      qty: 10,
      description: 'Low-and-slow shoulder with house BBQ sauce (not too sweet).',
      ingredients: ['Pork shoulder', 'Tomato', 'Molasses', 'Smoked paprika', 'Apple cider vinegar', 'Garlic', 'Onion'],
      nutrition: nf({ calories: 370, proteinG: 26, totalFatG: 21 }),
    },
  ],
  saturday: [
    {
      name: 'Saturday roast chicken & jus',
      price: 47,
      unitLabel: 'Whole bird (serves ~6)',
      qty: 10,
      description: 'Classic roast with pan jus and thyme — weekend comfort.',
      ingredients: ['Chicken', 'Thyme', 'Carrot', 'Celery', 'Onion', 'Butter', 'White wine'],
      nutrition: nf({ calories: 300, proteinG: 33, totalFatG: 13, cholesterolMg: 105 }),
    },
    {
      name: 'Grilled branzino fillets',
      price: 68,
      unitLabel: 'Half-tray (serves ~6)',
      qty: 6,
      description: 'Light fish with olive oil, lemon wheels, and herbs.',
      ingredients: ['Branzino', 'Lemon', 'Olive oil', 'Parsley', 'Garlic', 'Capers'],
      nutrition: nf({ calories: 240, proteinG: 26, totalFatG: 11, cholesterolMg: 60 }),
    },
    {
      name: 'Smoked brisket slices',
      price: 70,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 7,
      description: 'Sliced flat with peppercorn bark and pickle tray suggestion on invoice notes.',
      ingredients: ['Beef brisket', 'Black pepper', 'Kosher salt', 'Garlic', 'Onion powder', 'Paprika'],
      nutrition: nf({ calories: 380, proteinG: 30, totalFatG: 24, sodiumMg: 590 }),
    },
    {
      name: 'Lamb meatballs with tzatziki',
      price: 58,
      unitLabel: 'Half-tray (~22 meatballs)',
      qty: 8,
      description: 'Warm spices, cool yogurt sauce on the side.',
      ingredients: ['Ground lamb', 'Cumin', 'Mint', 'Greek yogurt', 'Cucumber', 'Garlic', 'Dill'],
      nutrition: nf({ calories: 330, proteinG: 24, totalFatG: 20, cholesterolMg: 85 }),
    },
    {
      name: 'Sweet chili glazed tofu steaks',
      price: 39,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 13,
      description: 'Pressed tofu slabs with sticky sweet chili glaze and sesame.',
      ingredients: ['Extra-firm tofu', 'Sweet chili sauce', 'Soy sauce', 'Sesame oil', 'Sesame seeds', 'Scallions'],
      nutrition: nf({ calories: 210, proteinG: 15, totalFatG: 9, sodiumMg: 520 }),
    },
  ],
  sunday: [
    {
      name: 'Sunday gravy meatballs',
      price: 46,
      unitLabel: 'Half-tray (~26 meatballs)',
      qty: 12,
      description: 'Beef-pork blend in a slow Sunday gravy — pairs with mashed sides.',
      ingredients: ['Ground beef', 'Ground pork', 'Tomato', 'Carrot', 'Onion', 'Garlic', 'Basil', 'Parmesan'],
      nutrition: nf({ calories: 310, proteinG: 22, totalFatG: 18, sodiumMg: 560 }),
    },
    {
      name: 'Herb roast turkey breast',
      price: 52,
      unitLabel: 'Half-tray (serves ~10)',
      qty: 9,
      description: 'Sliced breast with sage butter under the skin.',
      ingredients: ['Turkey breast', 'Sage', 'Butter', 'Garlic', 'Thyme', 'Chicken stock', 'White wine'],
      nutrition: nf({ calories: 250, proteinG: 35, totalFatG: 8, cholesterolMg: 85 }),
    },
    {
      name: 'Citrus fennel salmon',
      price: 63,
      unitLabel: 'Half-tray (serves ~6)',
      qty: 8,
      description: 'Sunday lighter option with shaved fennel salad paired on pickup notes.',
      ingredients: ['Salmon', 'Orange', 'Fennel', 'Olive oil', 'Dill', 'Red onion'],
      nutrition: nf({ calories: 270, proteinG: 27, totalFatG: 14, cholesterolMg: 65 }),
    },
    {
      name: 'Coffee-rubbed brisket ends',
      price: 64,
      unitLabel: 'Half-tray (serves ~7)',
      qty: 7,
      description: 'Rich ends with a mellow coffee rub — limited trays.',
      ingredients: ['Beef brisket', 'Coffee', 'Brown sugar', 'Smoked paprika', 'Garlic', 'Black pepper'],
      nutrition: nf({ calories: 390, proteinG: 29, totalFatG: 25 }),
    },
    {
      name: 'Chicken parmesan cutlets',
      price: 48,
      unitLabel: 'Half-tray (8 cutlets)',
      qty: 11,
      description: 'Crispy cutlets, marinara on the side to stay crisp for pickup.',
      ingredients: ['Chicken breast', 'Breadcrumbs', 'Parmesan', 'Egg', 'Marinara', 'Mozzarella', 'Basil'],
      nutrition: nf({ calories: 410, proteinG: 32, totalFatG: 18, sodiumMg: 720 }),
    },
  ],
};

const VEG_ROTATIONS: Record<WeekdayKey, Seed[]> = {
  monday: [
    {
      name: 'Roasted vegetable lasagna (no meat)',
      price: 42,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 10,
      description: 'Layers of zucchini, ricotta, marinara, and spinach.',
      ingredients: ['Zucchini', 'Spinach', 'Ricotta', 'Marinara', 'Lasagna sheets', 'Mozzarella', 'Parmesan'],
      nutrition: nf({ calories: 280, proteinG: 14, totalFatG: 12, sodiumMg: 580 }),
    },
    {
      name: 'Chickpea sweet potato tagine',
      price: 38,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 11,
      description: 'Warm spices, apricots, and cilantro — vegan as prepared.',
      ingredients: ['Chickpeas', 'Sweet potato', 'Tomato', 'Apricot', 'Cumin', 'Cinnamon', 'Cilantro'],
      nutrition: nf({ calories: 240, proteinG: 9, totalFatG: 6, dietaryFiberG: 8 }),
    },
    {
      name: 'Caprese orzo with pesto',
      price: 34,
      unitLabel: 'Half-tray (serves ~10)',
      qty: 12,
      description: 'Chilled orzo with mozzarella pearls, tomatoes, and basil pesto.',
      ingredients: ['Orzo', 'Cherry tomato', 'Mozzarella', 'Basil pesto', 'Pine nuts', 'Olive oil', 'Balsamic'],
      nutrition: nf({ calories: 320, proteinG: 12, totalFatG: 14, sodiumMg: 420 }),
    },
  ],
  tuesday: [
    {
      name: 'Stuffed poblano peppers',
      price: 40,
      unitLabel: 'Tray (8 halves)',
      qty: 9,
      description: 'Quinoa, black beans, corn, and pepper jack melt.',
      ingredients: ['Poblano pepper', 'Quinoa', 'Black beans', 'Corn', 'Pepper jack', 'Cumin', 'Lime'],
      nutrition: nf({ calories: 260, proteinG: 13, totalFatG: 10 }),
    },
    {
      name: 'Mushroom bourguignon (vegan)',
      price: 44,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 8,
      description: 'Hearty mushrooms and carrots in a red wine vegetable stock.',
      ingredients: ['Cremini mushroom', 'Carrot', 'Pearl onion', 'Red wine', 'Vegetable stock', 'Thyme', 'Tomato paste'],
      nutrition: nf({ calories: 220, proteinG: 8, totalFatG: 8, sodiumMg: 460 }),
    },
    {
      name: 'Greek mezze grain bowls (bulk)',
      price: 36,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 13,
      description: 'Farro with olives, cucumber, tomato, and whipped feta on the side.',
      ingredients: ['Farro', 'Cucumber', 'Tomato', 'Kalamata olive', 'Feta', 'Mint', 'Olive oil', 'Lemon'],
      nutrition: nf({ calories: 290, proteinG: 11, totalFatG: 12, sodiumMg: 520 }),
    },
  ],
  wednesday: [
    {
      name: 'Eggplant involtini',
      price: 41,
      unitLabel: 'Half-tray (12 rolls)',
      qty: 10,
      description: 'Grilled eggplant rolled with herbed ricotta and marinara.',
      ingredients: ['Eggplant', 'Ricotta', 'Marinara', 'Basil', 'Parmesan', 'Garlic', 'Oregano'],
      nutrition: nf({ calories: 270, proteinG: 13, totalFatG: 12, sodiumMg: 540 }),
    },
    {
      name: 'Coconut lime lentil dal',
      price: 35,
      unitLabel: 'Half-tray (serves ~10)',
      qty: 14,
      description: 'Red lentils with ginger, turmeric, and spinach.',
      ingredients: ['Red lentils', 'Coconut milk', 'Ginger', 'Turmeric', 'Spinach', 'Tomato', 'Cilantro'],
      nutrition: nf({ calories: 230, proteinG: 11, totalFatG: 8, dietaryFiberG: 7 }),
    },
    {
      name: 'Roasted cauliflower steaks',
      price: 37,
      unitLabel: 'Half-tray (6 steaks)',
      qty: 11,
      description: 'Charred cauliflower with romesco sauce.',
      ingredients: ['Cauliflower', 'Romesco', 'Almond', 'Red pepper', 'Smoked paprika', 'Olive oil'],
      nutrition: nf({ calories: 200, proteinG: 8, totalFatG: 11, sodiumMg: 400 }),
    },
  ],
  thursday: [
    {
      name: 'Wild mushroom risotto',
      price: 43,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 9,
      description: 'Arborio rice with porcini stock and crispy shallots.',
      ingredients: ['Arborio rice', 'Porcini', 'Shallot', 'White wine', 'Vegetable stock', 'Parmesan', 'Butter'],
      nutrition: nf({ calories: 340, proteinG: 11, totalFatG: 14, sodiumMg: 500 }),
    },
    {
      name: 'Black bean enchilada casserole',
      price: 39,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 12,
      description: 'Stacked corn tortillas, smoky salsa verde, queso fresco.',
      ingredients: ['Black beans', 'Corn tortilla', 'Salsa verde', 'Queso fresco', 'Onion', 'Cumin', 'Cilantro'],
      nutrition: nf({ calories: 300, proteinG: 14, totalFatG: 10, sodiumMg: 620 }),
    },
    {
      name: 'Thai basil tofu stir-fry',
      price: 37,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 13,
      description: 'Thai basil, chilies, bell peppers — medium spice.',
      ingredients: ['Tofu', 'Thai basil', 'Soy sauce', 'Garlic', 'Bell pepper', 'Bird’s eye chili', 'Vegetable oil'],
      nutrition: nf({ calories: 260, proteinG: 16, totalFatG: 12, sodiumMg: 680 }),
    },
  ],
  friday: [
    {
      name: 'Spinach artichoke baked shells',
      price: 38,
      unitLabel: 'Half-tray (serves ~10)',
      qty: 11,
      description: 'Jumbo shells stuffed with artichoke and three-cheese filling.',
      ingredients: ['Pasta shells', 'Spinach', 'Artichoke', 'Ricotta', 'Mozzarella', 'Parmesan', 'Garlic'],
      nutrition: nf({ calories: 310, proteinG: 15, totalFatG: 14, sodiumMg: 560 }),
    },
    {
      name: 'Crispy falafel platter',
      price: 36,
      unitLabel: 'Half-tray (~28 pieces)',
      qty: 14,
      description: 'Herb falafel with tahini sauce on the side.',
      ingredients: ['Chickpeas', 'Parsley', 'Cilantro', 'Cumin', 'Coriander', 'Onion', 'Tahini', 'Lemon'],
      nutrition: nf({ calories: 240, proteinG: 9, totalFatG: 11, sodiumMg: 480 }),
    },
    {
      name: 'Butternut squash mac & “cheese”',
      price: 40,
      unitLabel: 'Half-tray (serves ~10)',
      qty: 10,
      description: 'Cashew-nutritional yeast sauce with sage breadcrumbs.',
      ingredients: ['Butternut squash', 'Cashew', 'Nutritional yeast', 'Sage', 'Breadcrumbs', 'Garlic', 'Dijon'],
      nutrition: nf({ calories: 290, proteinG: 10, totalFatG: 12, sodiumMg: 430 }),
    },
  ],
  saturday: [
    {
      name: 'Summer ratatouille gratin',
      price: 41,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 10,
      description: 'Layered summer vegetables with herbed breadcrumbs.',
      ingredients: ['Zucchini', 'Eggplant', 'Tomato', 'Bell pepper', 'Onion', 'Herbs de Provence', 'Olive oil'],
      nutrition: nf({ calories: 210, proteinG: 6, totalFatG: 9, dietaryFiberG: 6 }),
    },
    {
      name: 'Crispy gochujang cauliflower',
      price: 39,
      unitLabel: 'Half-tray (serves ~8)',
      qty: 12,
      description: 'Baked then glazed — sweet heat.',
      ingredients: ['Cauliflower', 'Gochujang', 'Soy sauce', 'Sesame oil', 'Honey', 'Garlic', 'Ginger'],
      nutrition: nf({ calories: 220, proteinG: 7, totalFatG: 8, sodiumMg: 600 }),
    },
    {
      name: 'Mediterranean stuffed peppers',
      price: 42,
      unitLabel: 'Tray (10 halves)',
      qty: 9,
      description: 'Rice, lentils, herbs, pine nuts, and feta.',
      ingredients: ['Bell pepper', 'Brown rice', 'Green lentil', 'Feta', 'Pine nut', 'Mint', 'Lemon'],
      nutrition: nf({ calories: 270, proteinG: 12, totalFatG: 10, sodiumMg: 500 }),
    },
  ],
  sunday: [
    {
      name: 'Sunday vegetable pot pie (large format)',
      price: 44,
      unitLabel: 'Half-tray (deep)',
      qty: 8,
      description: 'Creamy root vegetable filling with flaky lid.',
      ingredients: ['Carrot', 'Parsnip', 'Peas', 'Celery', 'Cream', 'Vegetable stock', 'Puff pastry', 'Thyme'],
      nutrition: nf({ calories: 330, proteinG: 9, totalFatG: 18, sodiumMg: 540 }),
    },
    {
      name: 'Truffle Parmesan polenta cakes',
      price: 40,
      unitLabel: 'Half-tray (12 cakes)',
      qty: 10,
      description: 'Crisp-edged polenta with mushroom ragù on the side.',
      ingredients: ['Polenta', 'Parmesan', 'Truffle oil', 'Mushroom', 'Garlic', 'Thyme', 'Vegetable stock'],
      nutrition: nf({ calories: 310, proteinG: 10, totalFatG: 14, sodiumMg: 520 }),
    },
    {
      name: 'Green goddess pasta salad',
      price: 36,
      unitLabel: 'Half-tray (serves ~10)',
      qty: 13,
      description: 'Fusilli with peas, asparagus, and herb dressing.',
      ingredients: ['Fusilli', 'Asparagus', 'Peas', 'Basil', 'Parsley', 'Greek yogurt', 'Lemon', 'Garlic'],
      nutrition: nf({ calories: 280, proteinG: 11, totalFatG: 9, sodiumMg: 410 }),
    },
  ],
};

const SIDES_ROTATIONS: Record<WeekdayKey, Seed[]> = {
  monday: [
    {
      name: 'Roasted garlic mashed potatoes',
      price: 28,
      unitLabel: 'Half-tray',
      qty: 16,
      description: 'Yukon golds with roasted garlic and cultured butter.',
      ingredients: ['Yukon potato', 'Roasted garlic', 'Butter', 'Cream', 'Chives', 'Salt', 'White pepper'],
      nutrition: nf({ calories: 260, proteinG: 5, totalFatG: 12, totalCarbG: 32 }),
    },
    {
      name: 'Seasonal fruit & mint',
      price: 32,
      unitLabel: 'Large platter',
      qty: 12,
      description: 'Chef-selected melons, berries, and citrus with mint.',
      ingredients: ['Seasonal fruit', 'Mint', 'Lime zest'],
      nutrition: nf({ calories: 120, proteinG: 2, totalFatG: 0, totalCarbG: 28, totalSugarsG: 22 }),
    },
  ],
  tuesday: [
    {
      name: 'Charred corn esquites',
      price: 26,
      unitLabel: 'Half-tray',
      qty: 15,
      description: 'Off-the-cob street corn with lime and cotija.',
      ingredients: ['Corn', 'Cotija', 'Lime', 'Mayonnaise', 'Chili powder', 'Cilantro'],
      nutrition: nf({ calories: 240, proteinG: 7, totalFatG: 14, sodiumMg: 420 }),
    },
    {
      name: 'Buttered parsley noodles',
      price: 22,
      unitLabel: 'Half-tray',
      qty: 18,
      description: 'Simple egg noodles with parsley butter — kid friendly.',
      ingredients: ['Egg noodles', 'Butter', 'Parsley', 'Garlic', 'Parmesan'],
      nutrition: nf({ calories: 280, proteinG: 9, totalFatG: 11, sodiumMg: 360 }),
    },
  ],
  wednesday: [
    {
      name: 'Arugula pear salad',
      price: 30,
      unitLabel: 'Large bowl',
      qty: 14,
      description: 'Arugula, sliced pear, shaved parmesan, lemon vinaigrette on the side.',
      ingredients: ['Arugula', 'Pear', 'Parmesan', 'Lemon', 'Olive oil', 'Dijon', 'Honey', 'Pepper'],
      nutrition: nf({ calories: 180, proteinG: 6, totalFatG: 12, totalCarbG: 14 }),
    },
    {
      name: 'Honey glazed carrots',
      price: 24,
      unitLabel: 'Half-tray',
      qty: 17,
      description: 'Roasted rainbow carrots with thyme and honey.',
      ingredients: ['Carrot', 'Honey', 'Thyme', 'Olive oil', 'Salt'],
      nutrition: nf({ calories: 140, proteinG: 2, totalFatG: 5, totalCarbG: 22, totalSugarsG: 16 }),
    },
  ],
  thursday: [
    {
      name: 'Garlic green beans',
      price: 24,
      unitLabel: 'Half-tray',
      qty: 16,
      description: 'Blanched then sautéed with garlic and almond slivers.',
      ingredients: ['Green bean', 'Garlic', 'Almond', 'Olive oil', 'Lemon'],
      nutrition: nf({ calories: 120, proteinG: 4, totalFatG: 8, dietaryFiberG: 4 }),
    },
    {
      name: 'Ciabatta pull-apart with herb oil',
      price: 20,
      unitLabel: '2 loaves',
      qty: 20,
      description: 'Warm-again instructions included on invoice.',
      ingredients: ['Ciabatta', 'Olive oil', 'Rosemary', 'Garlic', 'Flaky salt'],
      nutrition: nf({ calories: 210, proteinG: 6, totalFatG: 7, totalCarbG: 30 }),
    },
  ],
  friday: [
    {
      name: 'Loaded smashed potatoes',
      price: 27,
      unitLabel: 'Half-tray',
      qty: 15,
      description: 'Crispy smashed reds with sour cream and chives on the side.',
      ingredients: ['Red potato', 'Sour cream', 'Chive', 'Butter', 'Garlic', 'Paprika'],
      nutrition: nf({ calories: 270, proteinG: 6, totalFatG: 13, totalCarbG: 32 }),
    },
    {
      name: 'Citrus fennel slaw',
      price: 26,
      unitLabel: 'Large bowl',
      qty: 14,
      description: 'Bright slaw with cabbage, fennel, and orange segments.',
      ingredients: ['Green cabbage', 'Fennel', 'Orange', 'Carrot', 'Apple cider vinegar', 'Olive oil', 'Honey'],
      nutrition: nf({ calories: 130, proteinG: 2, totalFatG: 7, totalCarbG: 15 }),
    },
  ],
  saturday: [
    {
      name: 'Grilled vegetable platter',
      price: 30,
      unitLabel: 'Large platter',
      qty: 12,
      description: 'Zucchini, peppers, red onion, balsamic drizzle separate.',
      ingredients: ['Zucchini', 'Bell pepper', 'Red onion', 'Balsamic vinegar', 'Olive oil', 'Basil'],
      nutrition: nf({ calories: 110, proteinG: 3, totalFatG: 6, totalCarbG: 12 }),
    },
    {
      name: 'Classic coleslaw',
      price: 22,
      unitLabel: 'Half-tray',
      qty: 18,
      description: 'Lightly creamy, celery seed finish.',
      ingredients: ['Green cabbage', 'Carrot', 'Mayonnaise', 'Apple cider vinegar', 'Celery seed', 'Sugar'],
      nutrition: nf({ calories: 190, proteinG: 2, totalFatG: 14, totalCarbG: 14 }),
    },
  ],
  sunday: [
    {
      name: 'Sunday dinner rolls (honey butter)',
      price: 18,
      unitLabel: '2 dozen rolls',
      qty: 22,
      description: 'Soft rolls with honey butter packets.',
      ingredients: ['Flour', 'Butter', 'Honey', 'Yeast', 'Milk', 'Egg', 'Salt'],
      nutrition: nf({ calories: 200, proteinG: 5, totalFatG: 8, totalCarbG: 28 }),
    },
    {
      name: 'Roasted Brussels with balsamic',
      price: 28,
      unitLabel: 'Half-tray',
      qty: 15,
      description: 'Crispy roasted with balsamic reduction cup.',
      ingredients: ['Brussels sprout', 'Balsamic reduction', 'Olive oil', 'Garlic', 'Pecorino'],
      nutrition: nf({ calories: 190, proteinG: 7, totalFatG: 11, dietaryFiberG: 5 }),
    },
  ],
};

export const WEEKDAY_MENU: Record<WeekdayKey, FoodItem[]> = (Object.keys(PROTEIN_ROTATIONS) as WeekdayKey[]).reduce(
  (acc, day) => {
    const proteins = PROTEIN_ROTATIONS[day].map((s, i) => item(day, 'protein', i, s));
    const veg = VEG_ROTATIONS[day].map((s, i) => item(day, 'vegetarian', i, s));
    const sides = SIDES_ROTATIONS[day].map((s, i) => item(day, 'sides', i, s));
    acc[day] = [...proteins, ...veg, ...sides];
    return acc;
  },
  {} as Record<WeekdayKey, FoodItem[]>,
);

export function getMenuForWeekday(day: WeekdayKey): FoodItem[] {
  return WEEKDAY_MENU[day];
}

export function getItemById(id: string): FoodItem | undefined {
  const menu = WEEKDAY_MENU[id.split('-')[0] as WeekdayKey];
  return menu?.find((m) => m.id === id);
}
